# -- 코드를 작성해주세요
# SELECT CASE WHEN LENGTH <= '10' THEN NULL
#     END AS MAX_LENGHT 
# FROM FISH_INFO
# ORDER BY MAX_LENGHT ASC
# LIMIT 1;


SELECT CONCAT(LENGTH, 'cm') AS MAX_LENGTH
FROM FISH_INFO
ORDER BY LENGTH DESC
LIMIT 1;

# SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH
# FROM FISH_INFO;