-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
CASE WHEN FREEZER_YN IS NULL THEN 'N' ELSE FREEZER_YN  END AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE ADDRESS LIKE '경기도%' -- 문제 조건: 경기도에 위치한 창고
ORDER BY WAREHOUSE_ID ASC;



# SELECT 
#     WAREHOUSE_ID, 
#     WAREHOUSE_NAME, 
#     ADDRESS, 
#     CASE 
#         WHEN FREEZER_YN IS NULL THEN 'N' 
#         ELSE FREEZER_YN 
#     END AS FREEZER_YN
# FROM FOOD_WAREHOUSE
# WHERE ADDRESS LIKE '경기도%' -- 문제 조건: 경기도에 위치한 창고
# ORDER BY WAREHOUSE_ID ASC;