-- 코드를 입력하세요
SELECT H.FLAVOR 
FROM FIRST_HALF H 
JOIN ICECREAM_INFO I 
    ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER > 3000
    AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY H.TOTAL_ORDER DESC



# SELECT H.FLAVOR 
# FROM FIRST_HALF H 
# JOIN ICECREAM_INFO I ON H.FLAVOR = I.FLAVOR -- IN이 아니라 ON을 써야 합니다.
# WHERE H.TOTAL_ORDER > 3000 -- 숫자는 따옴표 없이, TOTAL_ORDER는 FIRST_HALF 테이블에 있습니다.
#   AND I.INGREDIENT_TYPE = 'fruit_based' -- INGREDIENT_TYPE은 INFO 테이블에 있습니다.
# ORDER BY H.TOTAL_ORDER DESC; -- 주문량이 많은 순서이므로 DESC(내림차순)가 맞습니다.